"""Configuration file generation for SDP init wizard."""

from pathlib import Path


def generate_quality_gate(target_dir: Path, deps: dict[str, bool]) -> Path | None:
    """Generate quality-gate.toml configuration.

    Args:
        target_dir: Target directory
        deps: Detected optional dependencies

    Returns:
        Path to created file or None
    """
    import click

    quality_gate_file = target_dir / "quality-gate.toml"

    if quality_gate_file.exists():
        click.echo("⊘ quality-gate.toml already exists, skipping")
        return None

    # Generate configuration
    config = _get_quality_gate_config(deps)
    quality_gate_file.write_text(config)

    click.echo(f"✓ Created {quality_gate_file}")
    return quality_gate_file


def _get_quality_gate_config(deps: dict[str, bool]) -> str:
    """Get quality-gate.toml configuration.

    Args:
        deps: Detected optional dependencies

    Returns:
        TOML configuration string
    """
    # Base configuration
    config = """# SDP Quality Gate Configuration
# Auto-generated by sdp init

[coverage]
enabled = true
minimum = 80
fail_under = 80
exclude_patterns = [
    "*/tests/*",
    "*/test_*.py",
]

[complexity]
enabled = true
max_cc = 10
max_average_cc = 5

[file_size]
enabled = true
max_lines = 200
max_imports = 20
max_functions = 15

[type_hints]
enabled = true
require_return_types = true
require_param_types = true

[error_handling]
enabled = true
forbid_bare_except = true
forbid_pass_with_except = true

[architecture]
enabled = true
forbid_violations = [
    "domain -> application",
    "domain -> infrastructure",
    "domain -> presentation",
    "application -> infrastructure",
    "application -> presentation",
]
"""

    # Add Beads-specific configuration if detected
    if deps.get("Beads CLI"):
        config += """
# Beads integration
[testing]
enabled = true
require_test_for_new_code = true
"""

    return config


def create_env_template(target_dir: Path, deps: dict[str, bool]) -> Path | None:
    """Create .env.template file.

    Args:
        target_dir: Target directory
        deps: Detected optional dependencies

    Returns:
        Path to created file or None
    """
    import click

    env_template = target_dir / ".env.template"

    if env_template.exists():
        click.echo("⊘ .env.template already exists, skipping")
        return None

    # Generate template
    template = "# Environment Variables\n"
    template += "# Copy this file to .env and fill in values\n\n"

    # Add Telegram configuration if detected
    if deps.get("Telegram"):
        template += "# Telegram Notifications\n"
        template += "TELEGRAM_BOT_TOKEN=your_bot_token_here\n"
        template += "TELEGRAM_CHAT_ID=your_chat_id_here\n"
        template += "\n"

    # Add GitHub configuration if detected
    if deps.get("GitHub CLI (gh)"):
        template += "# GitHub Integration\n"
        template += "GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxx\n"
        template += "GITHUB_REPO=owner/repo\n"
        template += "\n"

    # Add Beads configuration if detected
    if deps.get("Beads CLI"):
        template += "# Beads Task Tracking\n"
        template += "BEADS_API_URL=http://localhost:8000\n"
        template += "\n"

    env_template.write_text(template)
    click.echo(f"✓ Created {env_template}")
    return env_template
