# golangci-lint configuration
# Note: v2.8.0 has breaking changes from v1.x
# TODO: Migrate to v2 config format
# See: https://golangci-lint.run/docs/configuration/

# For now, use --no-config flag or command-line args:
# golangci-lint run --no-config -E errcheck,gocyclo,gocognit,prealloc,staticcheck,ineffassign,unused,misspell ./...
