name: 'SDP Verify'
description: 'Run SDP verification gates on PRs with evidence tracking'
inputs:
  gates:
    description: 'Comma-separated list of gates to run (types, tests, coverage, evidence)'
    required: false
    default: 'types,tests,coverage'
  evidence-required:
    description: 'Whether to check evidence chain integrity'
    required: false
    default: 'true'
  comment:
    description: 'Whether to post PR comment with results'
    required: false
    default: 'true'
  version:
    description: 'SDP CLI version to install'
    required: false
    default: 'latest'
  working-directory:
    description: 'Working directory for SDP checks'
    required: false
    default: '.'
outputs:
  result:
    description: 'Verification result (pass/fail)'
    value: ${{ steps.verify.outputs.result }}
  gates-passed:
    description: 'Number of gates that passed'
    value: ${{ steps.verify.outputs.gates_passed }}
  gates-failed:
    description: 'Number of gates that failed'
    value: ${{ steps.verify.outputs.gates_failed }}
runs:
  using: 'composite'
  steps:
    - name: Install SDP CLI
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        WORKING_DIR="${{ inputs.working-directory }}"

        echo "Installing SDP CLI version: $VERSION"

        # Detect OS and architecture
        OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
        ARCH="$(uname -m)"

        # Map architecture names
        case "$ARCH" in
          x86_64|amd64)
            ARCH="amd64"
            ;;
          aarch64|arm64)
            ARCH="arm64"
            ;;
          *)
            echo "Unsupported architecture: $ARCH"
            exit 1
            ;;
        esac

        # Download from GitHub releases
        BINARY_NAME="sdp-${OS}-${ARCH}"

        if [ "$VERSION" = "latest" ]; then
          DOWNLOAD_URL="https://github.com/fall-out-bug/sdp/releases/latest/download/${BINARY_NAME}"
        else
          DOWNLOAD_URL="https://github.com/fall-out-bug/sdp/releases/download/${VERSION}/${BINARY_NAME}"
        fi

        echo "Downloading from: $DOWNLOAD_URL"

        # Use RUNNER_TEMP for binary storage (no sudo required)
        BIN_DIR="$RUNNER_TEMP/.bin"
        mkdir -p "$BIN_DIR"

        curl -fsSL "$DOWNLOAD_URL" -o "$BIN_DIR/sdp"
        chmod +x "$BIN_DIR/sdp"

        # Add to PATH for this and future steps
        echo "$BIN_DIR" >> $GITHUB_PATH

        echo "✅ SDP CLI installed to: $BIN_DIR"
        "$BIN_DIR/sdp" version || echo "Version command not available"

    - name: Run Verification Gates
      id: verify
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        GATES="${{ inputs.gates }}"
        EVIDENCE_REQUIRED="${{ inputs.evidence-required }}"

        echo "Running SDP verification gates..."
        echo "Gates: $GATES"
        echo "Evidence required: $EVIDENCE_REQUIRED"

        # Convert comma-separated gates to array
        IFS=',' read -ra GATE_ARRAY <<< "$GATES"

        PASSED=0
        FAILED=0
        RESULTS=()

        # Run each gate
        for gate in "${GATE_ARRAY[@]}"; do
          gate=$(echo "$gate" | xargs)  # trim whitespace
          echo ""
          echo "Running gate: $gate"

          case "$gate" in
            types)
              if sdp quality types 2>&1; then
                echo "✅ $gate passed"
                ((PASSED++))
                RESULTS+=("$gate: PASS")
              else
                echo "❌ $gate failed"
                ((FAILED++))
                RESULTS+=("$gate: FAIL")
              fi
              ;;
            tests)
              if go test ./... 2>&1; then
                echo "✅ $gate passed"
                ((PASSED++))
                RESULTS+=("$gate: PASS")
              else
                echo "❌ $gate failed"
                ((FAILED++))
                RESULTS+=("$gate: FAIL")
              fi
              ;;
            coverage)
              if sdp quality coverage 2>&1; then
                echo "✅ $gate passed"
                ((PASSED++))
                RESULTS+=("$gate: PASS")
              else
                echo "❌ $gate failed"
                ((FAILED++))
                RESULTS+=("$gate: FAIL")
              fi
              ;;
            evidence)
              if [ "$EVIDENCE_REQUIRED" = "true" ]; then
                if sdp log trace --verify 2>&1; then
                  echo "✅ $gate passed"
                  ((PASSED++))
                  RESULTS+=("$gate: PASS")
                else
                  echo "❌ $gate failed"
                  ((FAILED++))
                  RESULTS+=("$gate: FAIL")
                fi
              else
                echo "⊘ $gate skipped"
                RESULTS+=("$gate: SKIPPED")
              fi
              ;;
            *)
              echo "⚠️ Unknown gate: $gate"
              RESULTS+=("$gate: UNKNOWN")
              ;;
          esac
        done

        echo ""
        echo "=== Summary ==="
        echo "Passed: $PASSED"
        echo "Failed: $FAILED"
        echo ""
        printf '%s\n' "${RESULTS[@]}"

        # Set outputs
        echo "gates_passed=$PASSED" >> $GITHUB_OUTPUT
        echo "gates_failed=$FAILED" >> $GITHUB_OUTPUT

        # Set result and exit code (fail if any gate failed)
        if [ $FAILED -gt 0 ]; then
          echo "result=fail" >> $GITHUB_OUTPUT
          echo "exit_code=1" >> $GITHUB_OUTPUT
          echo ""
          echo "❌ Verification failed"
        else
          echo "result=pass" >> $GITHUB_OUTPUT
          echo "exit_code=0" >> $GITHUB_OUTPUT
          echo ""
          echo "✅ All gates passed"
        fi

    - name: Post PR Comment
      if: always()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        COMMENT_ENABLED: ${{ inputs.comment }}
        GATES_PASSED: ${{ steps.verify.outputs.gates_passed }}
        GATES_FAILED: ${{ steps.verify.outputs.gates_failed }}
        VERIFICATION_RESULT: ${{ steps.verify.outputs.result }}
        EVIDENCE_REQUIRED: ${{ inputs.evidence-required }}
        WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        set -euo pipefail

        # Skip if comment disabled
        if [ "$COMMENT_ENABLED" != "true" ]; then
          echo "⊘ PR comment disabled"
          exit 0
        fi

        # Check if we're in a PR context
        if [ "${{ github.event_name }}" != "pull_request" ]; then
          echo "⊘ Not a pull request, skipping comment"
          exit 0
        fi

        # Get PR number
        PR_NUMBER="${{ github.event.pull_request.number }}"
        if [ -z "$PR_NUMBER" ]; then
          echo "⊘ No PR number found, skipping comment"
          exit 0
        fi

        echo "Posting PR comment for #$PR_NUMBER..."

        # Build comment body
        STATUS_ICON="✅"
        if [ "$VERIFICATION_RESULT" = "fail" ]; then
          STATUS_ICON="❌"
        fi

        STATUS_TEXT="passed"
        if [ "$VERIFICATION_RESULT" = "fail" ]; then
          STATUS_TEXT="failed"
        fi

        TOTAL_GATES=$((GATES_PASSED + GATES_FAILED))
        WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        COMMENT_BODY="## SDP Verification ${STATUS_ICON}

        **Status:** Verification ${STATUS_TEXT}

        ### Gate Results

        | Gate | Status |
        |------|--------|"

        if [ $GATES_PASSED -gt 0 ]; then
          COMMENT_BODY="${COMMENT_BODY}
        | Passed | ${GATES_PASSED} |"
        fi

        if [ $GATES_FAILED -gt 0 ]; then
          COMMENT_BODY="${COMMENT_BODY}
        | Failed | ${GATES_FAILED} |"
        fi

        if [ $TOTAL_GATES -gt 0 ]; then
          COMMENT_BODY="${COMMENT_BODY}
        | **Total** | **${TOTAL_GATES}** |"
        fi

        COMMENT_BODY="${COMMENT_BODY}

        <details>
        <summary><b>Evidence Summary</b></summary>

        "

        # Add evidence statistics from sdp log stats
        if [ "$EVIDENCE_REQUIRED" = "true" ]; then
          COMMENT_BODY="${COMMENT_BODY}### Chain Integrity

        ✅ Evidence chain integrity verified

        ### Event Statistics

        "

          # Get evidence statistics
          EVIDENCE_STATS=$(sdp log stats 2>/dev/null || echo "")

          if [ -n "$EVIDENCE_STATS" ]; then
            # Parse and format stats
            TOTAL_EVENTS=$(echo "$EVIDENCE_STATS" | grep -o 'Total:[^[:space:]]*[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$' || echo "N/A")
            PLAN_EVENTS=$(echo "$EVIDENCE_STATS" | grep -o 'plan:[^[:space:]]*[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$' || echo "0")
            GENERATION_EVENTS=$(echo "$EVIDENCE_STATS" | grep -o 'generation:[^[:space:]]*[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$' || echo "0")
            VERIFICATION_EVENTS=$(echo "$EVIDENCE_STATS" | grep -o 'verification:[^[:space:]]*[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$' || echo "0")

            COMMENT_BODY="${COMMENT_BODY}| Metric | Count |
|---------|-------|
| Total Events | ${TOTAL_EVENTS} |
| Plan Events | ${PLAN_EVENTS} |
| Generation Events | ${GENERATION_EVENTS} |
| Verification Events | ${VERIFICATION_EVENTS} |"
          else
            COMMENT_BODY="${COMMENT_BODY}_Unable to retrieve evidence statistics_"
          fi
        else
          COMMENT_BODY="${COMMENT_BODY}### Chain Integrity

        ⊘ Evidence chain verification not required"
        fi

        COMMENT_BODY="${COMMENT_BODY}

        </details>

        ---
        *View full details in [Workflow Run](${WORKFLOW_URL})*"

        # Look for existing comment
        EXISTING_COMMENT_ID=$(gh api \
          "repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
          --jq '.[] | select(.body | startswith("## SDP Verification")) | .id' \
          2>/dev/null || echo "")

        if [ -n "$EXISTING_COMMENT_ID" ]; then
          # Update existing comment
          echo "Updating existing comment #$EXISTING_COMMENT_ID"
          gh api \
            --method PATCH \
            "repos/${{ github.repository }}/issues/comments/${EXISTING_COMMENT_ID}" \
            -f body="$COMMENT_BODY" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --silent
        else
          # Create new comment
          echo "Creating new comment"
          gh api \
            --method POST \
            "repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            -f body="$COMMENT_BODY" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --silent
        fi

        echo "✅ PR comment posted"

        # Exit with verification result (to fail the workflow if gates failed)
        if [ "$VERIFICATION_RESULT" = "fail" ]; then
          exit 1
        fi

